base_url = "https://thiagomajesk.github.io"
compile_sass = false
build_search_index = false
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]

taxonomies = [
    { name = "categories", feed = true, paginate_by = 10 },
    { name = "tags", feed = true, paginate_by = 10 },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true


[extra]
title = "Thiago's Guide To Everything"
keywords = ["zola", "blog"]
